// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package dbsql

import (
	"context"
)

const checkDatabase = `-- name: CheckDatabase :one
select 1::int as ok
`

func (q *Queries) CheckDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkDatabase)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
