// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsql

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoreSession struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	UserAgent  pgtype.Text
	IpAddress  *netip.Addr
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type CoreUser struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
