// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsql

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoreEvent struct {
	ID          pgtype.UUID
	PlaygroupID pgtype.UUID
	Title       string
	Description string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	LocationID  pgtype.UUID
	Visibility  string
	InviteToken pgtype.Text
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CoreEventGuest struct {
	ID        pgtype.UUID
	EventID   pgtype.UUID
	RsvpID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoreEventHost struct {
	ID                pgtype.UUID
	EventID           pgtype.UUID
	UserID            pgtype.UUID
	AddressVisibility string
	CreatedAt         pgtype.Timestamptz
}

type CoreEventLocation struct {
	ID            pgtype.UUID
	PlaygroupID   pgtype.UUID
	Name          string
	AddressLine1  pgtype.Text
	AddressLine2  pgtype.Text
	City          pgtype.Text
	StateProvince pgtype.Text
	PostalCode    pgtype.Text
	Country       pgtype.Text
	Notes         string
	CreatedBy     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type CoreEventReminder struct {
	ID           pgtype.UUID
	EventID      pgtype.UUID
	ScheduledFor pgtype.Timestamptz
	ReminderType string
	Status       string
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CoreEventRsvp struct {
	ID                  pgtype.UUID
	EventID             pgtype.UUID
	UserID              pgtype.UUID
	GuestName           pgtype.Text
	Status              string
	ArrivalTime         pgtype.Timestamptz
	LeavingTime         pgtype.Timestamptz
	GuestCount          int32
	TravelBufferMinutes pgtype.Int4
	Notes               string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CoreHouseRule struct {
	ID              pgtype.UUID
	PlaygroupID     pgtype.UUID
	Title           string
	Body            string
	VisibleToGuests bool
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CorePlaygroup struct {
	ID          pgtype.UUID
	Name        string
	Slug        string
	Description string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CorePlaygroupInvite struct {
	ID          pgtype.UUID
	PlaygroupID pgtype.UUID
	TokenHash   []byte
	Role        string
	Email       pgtype.Text
	MaxUses     pgtype.Int4
	UsedCount   int32
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type CorePlaygroupMembership struct {
	ID          pgtype.UUID
	PlaygroupID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	DisplayName pgtype.Text
	JoinedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CorePlaygroupSetting struct {
	PlaygroupID            pgtype.UUID
	DefaultEventVisibility string
	AllowGuestRsvps        bool
	ShowMemberDecklists    bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type CoreSession struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  []byte
	UserAgent  pgtype.Text
	IpAddress  *netip.Addr
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type CoreUser struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OpsBackgroundJob struct {
	ID          pgtype.UUID
	Queue       string
	JobType     string
	Payload     []byte
	RunAt       pgtype.Timestamptz
	LockedAt    pgtype.Timestamptz
	LockedBy    pgtype.Text
	Attempts    int32
	MaxAttempts int32
	LastError   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type OpsEmailDelivery struct {
	ID           pgtype.UUID
	ToAddress    string
	Subject      string
	BodyText     pgtype.Text
	BodyHtml     pgtype.Text
	Status       string
	ErrorMessage pgtype.Text
	SentAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
