// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ops.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireNextBackgroundJob = `-- name: AcquireNextBackgroundJob :one
update ops.background_jobs
set 
  locked_at = now(),
  locked_by = $1,
  attempts = attempts + 1,
  updated_at = now()
where id = (
  select id from ops.background_jobs
  where run_at <= now() and locked_at is null
  order by run_at asc
  limit 1
  for update skip locked
)
returning id, queue, job_type, payload, run_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

func (q *Queries) AcquireNextBackgroundJob(ctx context.Context, lockedBy pgtype.Text) (OpsBackgroundJob, error) {
	row := q.db.QueryRow(ctx, acquireNextBackgroundJob, lockedBy)
	var i OpsBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.JobType,
		&i.Payload,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeBackgroundJob = `-- name: CompleteBackgroundJob :exec
delete from ops.background_jobs where id = $1
`

func (q *Queries) CompleteBackgroundJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeBackgroundJob, id)
	return err
}

const failBackgroundJob = `-- name: FailBackgroundJob :exec
update ops.background_jobs
set
  locked_at = null,
  locked_by = null,
  last_error = $2,
  run_at = now() + (pow(2, attempts) * interval '1 minute'),
  updated_at = now()
where id = $1
`

type FailBackgroundJobParams struct {
	ID        pgtype.UUID
	LastError pgtype.Text
}

func (q *Queries) FailBackgroundJob(ctx context.Context, arg FailBackgroundJobParams) error {
	_, err := q.db.Exec(ctx, failBackgroundJob, arg.ID, arg.LastError)
	return err
}

const getEmailDelivery = `-- name: GetEmailDelivery :one
select id, to_address, subject, body_text, body_html, status, error_message, sent_at, created_at, updated_at from ops.email_deliveries where id = $1
`

func (q *Queries) GetEmailDelivery(ctx context.Context, id pgtype.UUID) (OpsEmailDelivery, error) {
	row := q.db.QueryRow(ctx, getEmailDelivery, id)
	var i OpsEmailDelivery
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBackgroundJob = `-- name: InsertBackgroundJob :one
insert into ops.background_jobs (
  queue, job_type, payload, run_at
) values (
  $1, $2, $3, $4
) returning id, queue, job_type, payload, run_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

type InsertBackgroundJobParams struct {
	Queue   string
	JobType string
	Payload []byte
	RunAt   pgtype.Timestamptz
}

func (q *Queries) InsertBackgroundJob(ctx context.Context, arg InsertBackgroundJobParams) (OpsBackgroundJob, error) {
	row := q.db.QueryRow(ctx, insertBackgroundJob,
		arg.Queue,
		arg.JobType,
		arg.Payload,
		arg.RunAt,
	)
	var i OpsBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.JobType,
		&i.Payload,
		&i.RunAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEmailDelivery = `-- name: InsertEmailDelivery :one
insert into ops.email_deliveries (
  to_address, subject, body_text, body_html
) values (
  $1, $2, $3, $4
) returning id, to_address, subject, body_text, body_html, status, error_message, sent_at, created_at, updated_at
`

type InsertEmailDeliveryParams struct {
	ToAddress string
	Subject   string
	BodyText  pgtype.Text
	BodyHtml  pgtype.Text
}

func (q *Queries) InsertEmailDelivery(ctx context.Context, arg InsertEmailDeliveryParams) (OpsEmailDelivery, error) {
	row := q.db.QueryRow(ctx, insertEmailDelivery,
		arg.ToAddress,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
	)
	var i OpsEmailDelivery
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmailDeliveryStatus = `-- name: UpdateEmailDeliveryStatus :one
update ops.email_deliveries
set
  status = $2,
  error_message = $3,
  sent_at = case when $2 = 'sent' then now() else sent_at end,
  updated_at = now()
where id = $1
returning id, to_address, subject, body_text, body_html, status, error_message, sent_at, created_at, updated_at
`

type UpdateEmailDeliveryStatusParams struct {
	ID           pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateEmailDeliveryStatus(ctx context.Context, arg UpdateEmailDeliveryStatusParams) (OpsEmailDelivery, error) {
	row := q.db.QueryRow(ctx, updateEmailDeliveryStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i OpsEmailDelivery
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
