// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into core.sessions (user_id, token_hash, user_agent, ip_address, expires_at)
values ($1, $2, $3, $4, $5)
returning id, user_id, token_hash, user_agent, ip_address, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	UserAgent pgtype.Text
	IpAddress *netip.Addr
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CoreSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CoreSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into core.users (email, display_name, password_hash)
values ($1, $2, $3)
returning id, email, display_name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CoreUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
select id, user_id, token_hash, user_agent, ip_address, created_at, last_seen_at, expires_at, revoked_at
from core.sessions
where token_hash = $1
  and revoked_at is null
  and expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (CoreSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i CoreSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, display_name, password_hash, created_at, updated_at
from core.users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, display_name, password_hash, created_at, updated_at
from core.users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (CoreUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i CoreUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
update core.sessions
set revoked_at = now()
where token_hash = $1
  and revoked_at is null
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}
